language: python
dist: xenial
python: '3.6'
branches:
  only:
  - master
install:
- pip install pipenv
- pipenv install
script:
- pipenv run pelican
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: output
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository
  on:
    branch: master
